# PRD (production) environment overrides for flask-aws-monitor
replicaCount: 3

image:
  tag: latest

service:
  type: LoadBalancer

ingress:
  enabled: true
  host: flask-monitor.prod.local

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 1Gi
