# DEV environment overrides for flask-aws-monitor
replicaCount: 1

image:
  tag: dev

service:
  type: ClusterIP

ingress:
  enabled: true
  host: flask-monitor.dev.local

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi
